apiVersion: apps/v1
kind: Deployment
metadata:
  name: Ptstatus
  labels:
    app: Ptstatus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Ptstatus
  template:
    metadata:
      labels:
        app: Ptstatus
    spec:
      containers:
        - name: Ptstatus
          image: username/Ptstatus:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5